# Generated by Django 5.0.4 on 2024-04-26 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingpong', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blade', models.CharField(max_length=100, verbose_name='底板')),
                ('forehand_rubber', models.CharField(max_length=100, verbose_name='正手胶皮')),
                ('backhand_rubber', models.CharField(max_length=100, verbose_name='反手胶皮')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=1, verbose_name='性别')),
            ],
        ),
    ]
